using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.IO;
using System.Reflection;
using System.Text;
using System.Xml.Serialization;


namespace MBM.Entities
{
	public class RecordType1 : IComparable, MBM.Entities.IMBMPrinter, MBM.Entities.ICurrencyConvertor
	{
		#region Data

		/// <summary>
		/// Unique Identifier
		/// </summary>
		public int ID { get; set; }

		/// <summary>
		/// Type of Record Entry
		/// </summary>
		public int? RecordType { get; set; }

		/// <summary>
		/// Billing Account Number (BAN)
		/// </summary>
		public string BAN { get; set; }

		/// <summary>
		/// Invoice Identifier
		/// </summary>
		public int InvoiceID { get; set; }

		/// <summary>
		/// Invoice Number
		/// </summary>
		public string InvoiceNumber { get; set; }

		/// <summary>
		/// Invoice Number displayed in output friendly format
		/// </summary>
		/// <remarks>
		/// Invoice Display was created because the Invoice Number needed for the Canadian bill
		/// is a compound of the BAN + trailing edge of the InvoiceNumber. If the BAN is CA202002
		/// and the Invoice is CA10001 then the InvoiceDisplay for Canada is CA20200210001.
		/// </remarks>
		public string InvoiceDisplay
		{
			get
			{
                return InvoiceNumber;

                //if (InvoiceType == InvoiceTypeEnum.Canada)
                //{
                //    return BAN + InvoiceNumber.Substring(2);
                //}
                //else
                //{
                //    return InvoiceNumber;
                //}
			}
		}

		/// <summary>
		/// Invoice Type
		/// </summary>
		//public InvoiceTypeEnum InvoiceType { get; set; } //ER#6752

		/// <summary>
		/// Name of the Vendor + identifying code (CBTS CA, CBTS, etc.)
		/// </summary>
		public string VendorName { get; set; }

		/// <summary>
		/// Name of the State or Province
		/// </summary>
		public string Locality { get; set; }

		/// <summary>
		/// Identifier of the currency conversion rate
		/// </summary>
		public int CurrencyConversionID { get; set; }

		/// <summary>
		/// Date call was made
		/// </summary>
		public DateTime CallDate { get; set; }

		/// <summary>
		/// Time of the call
		/// </summary>
		public string CallTime { get; set; }

		/// <summary>
		/// when the call was recorded
		/// </summary>
		public string DateOfRecord { get; set; }

		/// <summary>
		/// Date of the Bill
		/// </summary>
		public string BillDate { get; set; }

		/// <summary>
		/// GE Single Sign-On
		/// </summary>
		public string SSO { get; set; }

		/// <summary>
		/// Originating number
		/// </summary>
		public string FromNumber { get; set; }

		/// <summary>
		/// Destination number
		/// </summary>
		public string ToNumber { get; set; }

		/// <summary>
		/// DID Phone number
		/// </summary>
		public string DIDNumber { get; set; }

		/// <summary>
		/// Unknown
		/// </summary>
		public string FromToNumber { get; set; }

		/// <summary>
		/// Amount of revenue generated by call
		/// </summary>
		public decimal? Revenue { get; set; }

		/// <summary>
		/// when the call was connected
		/// </summary>
		public string ConnectTime { get; set; }

		/// <summary>
		/// Duration of the call
		/// </summary>
		public decimal? Duration { get; set; }

		/// <summary>
		/// Billing number in NAP standard
		/// </summary>
		public string BillingNumberNorthAmericanStandard { get; set; }

		/// <summary>
		/// Originating city
		/// </summary>
		public string FromCity { get; set; }

		/// <summary>
		/// Originating State/Providence
		/// </summary>
		public string FromState { get; set; }

		/// <summary>
		/// Destination City
		/// </summary>
		public string ToCity { get; set; }

		/// <summary>
		/// Destination State/Providence
		/// </summary>
		public string ToState { get; set; }

		/// <summary>
		/// Billing settlement code
		/// </summary>
		public int? SettlementCode { get; set; }

		/// <summary>
		/// Type of charge (call, equipment, service, etc.)
		/// </summary>
		public string ChargeDescription { get; set; }

		/// <summary>
		/// Provider of the service
		/// </summary>
		public string Provider { get; set; }

		/// <summary>
		/// Unknown
		/// </summary>
		public string ChargeOrientation { get; set; }

		/// <summary>
		/// Unknown
		/// </summary>
		public string OriginalFromNumber { get; set; }

        /// <summary>
        /// LegalEntity
        /// </summary>
        public string LegalEntity { get; set; }

        //cbe8967
        /// <summary>
        /// CountofCharges
        /// </summary>
        public int? CountOfCharges { get; set; }

        /// <summary>
        /// ChargeAmount
        /// </summary>
        public decimal? ChargeAmount { get; set; }


		#endregion

		#region Output

		static List<KeyValuePair<string, string>> layout = new List<KeyValuePair<string,string>>()
		{
			new KeyValuePair<string, string>("record_type", "RecordType"),
			new KeyValuePair<string, string>("billing_account_number", "BAN"),
			new KeyValuePair<string, string>("invoice_number", "InvoiceDisplay"),
			new KeyValuePair<string, string>("bill_date", "BillDate"),
			//new KeyValuePair<string, string>("SSO", "SSO"),
			new KeyValuePair<string, string>("originating_number", "FromNumber"),
			new KeyValuePair<string, string>("terminating_number", "ToNumber"),
			new KeyValuePair<string, string>("charge_amount", "Revenue"),
			new KeyValuePair<string, string>("record_date", "DateOfRecord"),
			new KeyValuePair<string, string>("record_time", "ConnectTime"),
			new KeyValuePair<string, string>("billable_minutes", "Duration"),
			new KeyValuePair<string, string>("na_billing_number", "BillingNumberNorthAmericanStandard"),
			new KeyValuePair<string, string>("originating_city", "FromCity"),
			new KeyValuePair<string, string>("originating_state", "FromState"),
			new KeyValuePair<string, string>("terminating_city", "ToCity"),
			new KeyValuePair<string, string>("terminating_state", "ToState"),
			new KeyValuePair<string, string>("settlement_code", "SettlementCode"),
			new KeyValuePair<string, string>("charge_description", "ChargeDescription"),
			new KeyValuePair<string, string>("provider", "Provider"),
			new KeyValuePair<string, string>("vendor_name", "VendorName"),
			new KeyValuePair<string, string>("state", "Locality"),
            new KeyValuePair<string, string>("legal_entity", "LegalEntity"),
		};

		static public List<string> MBMHeader
		{
			get
			{
				List<string> header = new List<string>();

				foreach (KeyValuePair<string, string> kvp in layout)
				{
					header.Add(kvp.Key);
				}

				return header;
			}
		}

		public OrderedDictionary MBMOutput
		{
			get
			{
				OrderedDictionary outformat = new OrderedDictionary();

				foreach (KeyValuePair<string, string> kvp in layout)
				{
					Type t = this.GetType();
					PropertyInfo pi = t.GetProperty(kvp.Value, BindingFlags.Instance|BindingFlags.Public|BindingFlags.DeclaredOnly);
					if (pi != null)
					{
						object value = pi.GetValue(this, null);
						outformat.Add(kvp.Key, ((value != null) ? value.ToString() : string.Empty));
					}
					else
					{
						outformat.Add(kvp.Key, "**ERROR**");
					}
				}

				return outformat;
			}
		}

		#endregion

		#region CurrencyConvertor

		/// <summary>
		/// Existing Currency
		/// </summary>
		public CurrencyConversion CurrentCurrency { get; set; }

		/// <summary>
		/// Convert all money values to new currency
		/// </summary>
		/// <param name="conv"></param>
		public void ConvertCurrency(CurrencyConversion conv)
		{
			if (CurrentCurrency == null || conv == null)
			{
				throw new Exception("Cannot convert currency. Missing converter");
			}

			if (Revenue.HasValue)
			{
				if (CurrentCurrency.ID != conv.ID)
				{
					Revenue = ((Revenue.Value / CurrentCurrency.ConversionRate) * conv.ConversionRate);
				}

				Revenue = Decimal.Round(Revenue.Value, 4);
			}
			
			CurrencyConversionID = conv.ID;
		}

		#endregion

		#region Comparer

		public enum Sort
		{
			/// <summary>
			/// YUnique Identifier
			/// </summary>
			ID = 1,
			/// <summary>
			/// Record Type identifier
			/// </summary>
			RecordType = 2,
		}

		public static System.Collections.Generic.IComparer<RecordType1> GetComparer(Sort field)
		{
			switch (field)
			{
				case Sort.ID:
					return new IdComparer();
				case Sort.RecordType:
					return new RecordTypeComparer();
				default:
					return new IdComparer();
			}
		}


		protected sealed class IdComparer : System.Collections.Generic.IComparer<RecordType1>
		{
			int System.Collections.Generic.IComparer<RecordType1>.Compare(RecordType1 lhs, RecordType1 rhs)
			{
				return lhs.ID.CompareTo(rhs.ID);
			}
		}
		protected sealed class RecordTypeComparer : System.Collections.Generic.IComparer<RecordType1>
		{
			int System.Collections.Generic.IComparer<RecordType1>.Compare(RecordType1 lhs, RecordType1 rhs)
			{
				// NULL values preceede real values
				if (!lhs.RecordType.HasValue)
				{
					if (!rhs.RecordType.HasValue)
					{
						return 0;
					}

					return -1;
				}
				else if (!rhs.RecordType.HasValue)
				{
					return 1;
				}

				int status = lhs.RecordType.Value.CompareTo(rhs.RecordType.Value);
				if (status == 0)
				{
					status = lhs.ID.CompareTo(rhs.ID);
				}

				return status;
			}
		}


		/// <summary>
		/// Compare objects of the same type
		/// </summary>
		/// <param name="rhs">right-hand side of compare</param>
		/// <returns>1 on greater; 0 on equal; -1 on lesser</returns>
		int IComparable.CompareTo(Object rhs)
		{
			if (!(rhs is RecordType1))
			{
				throw new ArgumentException("Argument is not an USRecordType1", "rhs");
			}
			RecordType1 r = (RecordType1)rhs;
			return this.CompareTo(r);
		}

		/// <summary>
		/// Compare objects of the same type
		/// </summary>
		/// <param name="rhs">right-hand side of compare</param>
		/// <returns>1 on greater; 0 on equal; -1 on lesser</returns>
		public int CompareTo(RecordType1 rhs)
		{
			return this.ID.CompareTo(rhs.ID);
		}

		/// <summary>
		/// Less than operator
		/// </summary>
		/// <param name="left">left-hand side</param>
		/// <param name="right">right-hand side</param>
		/// <returns>true if left-hand side is less than the right</returns>
		public static bool operator <(RecordType1 left, RecordType1 right)
		{
			return left.CompareTo(right) < 0;
		}

		/// <summary>
		/// Less than or equal operator
		/// </summary>
		/// <param name="left">left-hand side</param>
		/// <param name="right">right-hand side</param>
		/// <returns>true if left-hand side is less than or equal to the right</returns>
		public static bool operator <=(RecordType1 left, RecordType1 right)
		{
			return left.CompareTo(right) <= 0;
		}

		/// <summary>
		/// Greater than operator
		/// </summary>
		/// <param name="left">left-hand side</param>
		/// <param name="right">right-hand side</param>
		/// <returns>true if left-hand side is greater than the right</returns>
		public static bool operator >(RecordType1 left, RecordType1 right)
		{
			return left.CompareTo(right) > 0;
		}

		/// <summary>
		/// Greater than or equal operator
		/// </summary>
		/// <param name="left">left-hand side</param>
		/// <param name="right">right-hand side</param>
		/// <returns>true if left-hand side is greater than or equal to the right</returns>
		public static bool operator >=(RecordType1 left, RecordType1 right)
		{
			return left.CompareTo(right) >= 0;
		}


		#endregion

		#region Serializer

		/// <summary>
		/// Deserializes an object(s) into this class
		/// </summary>
		/// <param name="ms">XML memory stream</param>
		/// <returns>list of objects within the stream</returns>
		/// <remarks>this method is provides to ease transition of the same objects across namespace</remarks>
		public static List<RecordType1> DeserializeFromXML(
			MemoryStream ms
			)
		{
			XmlSerializer deserializer = new XmlSerializer(typeof(List<RecordType1>));
			List<RecordType1> objects;
			objects = (List<RecordType1>)deserializer.Deserialize(ms);
			ms.Close();

			return objects;
		}

		#endregion
	}
}
