//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automate.DataAccess.edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AutomateEntities : DbContext
    {
        public AutomateEntities()
            : base("name=AutomateEntities")
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 0;
        }

    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mbm_Invoice> mbm_Invoice { get; set; }
        public virtual DbSet<mbm_InvoiceTypes> mbm_InvoiceTypes { get; set; }
        public virtual DbSet<mbm_ProcessWorkFlowStatus> mbm_ProcessWorkFlowStatus { get; set; }
        public virtual DbSet<MBMAutomateStatu> MBMAutomateStatus { get; set; }
        public virtual DbSet<TokenHistory> TokenHistories { get; set; }
        public virtual DbSet<ApplicationLog> ApplicationLogs { get; set; }
        public virtual DbSet<ExceptionLog> ExceptionLogs { get; set; }
        public virtual DbSet<ProcessLog> ProcessLogs { get; set; }
    
        public virtual ObjectResult<get_AssoicateAccountsByInvoiceTypeId_Result> get_AssoicateAccountsByInvoiceTypeId(Nullable<int> invoiceTypeId)
        {
            var invoiceTypeIdParameter = invoiceTypeId.HasValue ?
                new ObjectParameter("InvoiceTypeId", invoiceTypeId) :
                new ObjectParameter("InvoiceTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_AssoicateAccountsByInvoiceTypeId_Result>("get_AssoicateAccountsByInvoiceTypeId", invoiceTypeIdParameter);
        }
    
        public virtual ObjectResult<get_AssoicateFileTypesByInvoiceTypeId_Result> get_AssoicateFileTypesByInvoiceTypeId(Nullable<int> invoiceTypeId)
        {
            var invoiceTypeIdParameter = invoiceTypeId.HasValue ?
                new ObjectParameter("InvoiceTypeId", invoiceTypeId) :
                new ObjectParameter("InvoiceTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_AssoicateFileTypesByInvoiceTypeId_Result>("get_AssoicateFileTypesByInvoiceTypeId", invoiceTypeIdParameter);
        }
    
        public virtual int get_CRMInputData(string invoiceNumber, string loggedInUser)
        {
            var invoiceNumberParameter = invoiceNumber != null ?
                new ObjectParameter("InvoiceNumber", invoiceNumber) :
                new ObjectParameter("InvoiceNumber", typeof(string));
    
            var loggedInUserParameter = loggedInUser != null ?
                new ObjectParameter("LoggedInUser", loggedInUser) :
                new ObjectParameter("LoggedInUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("get_CRMInputData", invoiceNumberParameter, loggedInUserParameter);
        }
    
        public virtual ObjectResult<get_InvoiceDetailsByNumber_Result> get_InvoiceDetailsByNumber(Nullable<int> invoiceID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("invoiceID", invoiceID) :
                new ObjectParameter("invoiceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_InvoiceDetailsByNumber_Result>("get_InvoiceDetailsByNumber", invoiceIDParameter);
        }
    
        public virtual ObjectResult<get_InvoiceFileTypes_ByInvoiceId_Result> get_InvoiceFileTypes_ByInvoiceId(Nullable<int> invoiceTypeId)
        {
            var invoiceTypeIdParameter = invoiceTypeId.HasValue ?
                new ObjectParameter("InvoiceTypeId", invoiceTypeId) :
                new ObjectParameter("InvoiceTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_InvoiceFileTypes_ByInvoiceId_Result>("get_InvoiceFileTypes_ByInvoiceId", invoiceTypeIdParameter);
        }
    
        public virtual ObjectResult<Get_InvoiceFileUploads_ByInvoiceId_Result> Get_InvoiceFileUploads_ByInvoiceId(Nullable<int> invoiceID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_InvoiceFileUploads_ByInvoiceId_Result>("Get_InvoiceFileUploads_ByInvoiceId", invoiceIDParameter);
        }
    
        public virtual ObjectResult<get_InvoiceNumbersByTypeId_Result> get_InvoiceNumbersByTypeId(Nullable<int> invoiceID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("invoiceID", invoiceID) :
                new ObjectParameter("invoiceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_InvoiceNumbersByTypeId_Result>("get_InvoiceNumbersByTypeId", invoiceIDParameter);
        }
    
        public virtual ObjectResult<get_InvoiceType_Result> get_InvoiceType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_InvoiceType_Result>("get_InvoiceType");
        }
    
        public virtual ObjectResult<Get_MBM_ComparisonResult_Result> Get_MBM_ComparisonResult(Nullable<int> invoiceId)
        {
            var invoiceIdParameter = invoiceId.HasValue ?
                new ObjectParameter("InvoiceId", invoiceId) :
                new ObjectParameter("InvoiceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_MBM_ComparisonResult_Result>("Get_MBM_ComparisonResult", invoiceIdParameter);
        }

        public ObjectResult<Get_MBM_ComparisonResultCSG> Get_MBM_ComparisonResultCSG(Nullable<int> invoiceId)
        {
            var invoiceIdParameter = invoiceId.HasValue ?
                new ObjectParameter("InvoiceId", invoiceId) :
                new ObjectParameter("InvoiceId", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_MBM_ComparisonResultCSG>("Get_MBM_ComparisonResultCSG", invoiceIdParameter);
        }
    
        public virtual ObjectResult<Get_UnprocessedMBMComparisonResult_Result> Get_UnprocessedMBMComparisonResult(Nullable<int> invoiceId)
        {
            var invoiceIdParameter = invoiceId.HasValue ?
                new ObjectParameter("InvoiceId", invoiceId) :
                new ObjectParameter("InvoiceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_UnprocessedMBMComparisonResult_Result>("Get_UnprocessedMBMComparisonResult", invoiceIdParameter);
        }
    
        public virtual int insert_Invoice(Nullable<int> invoiceTypeID, string invoiceNumber, Nullable<int> billingMonth, Nullable<int> billingYear, Nullable<int> defaultImportCurrencyID, string userName, string status, string lastAction, string recordType1_Status, Nullable<System.DateTime> recordType1_DateTime, string recordType2_Status, Nullable<System.DateTime> recordType2_DateTime, string recordType3_Status, Nullable<System.DateTime> recordType3_DateTime, string recordType4_Status, Nullable<System.DateTime> recordType4_DateTime, string recordType5_Status, Nullable<System.DateTime> recordType5_DateTime, string billingFileExport_Status, Nullable<System.DateTime> billingFileExport_DateTime, string billingFileExport_Path, Nullable<int> exportCurrencyID, Nullable<int> serviceDeskSnapshotID)
        {
            var invoiceTypeIDParameter = invoiceTypeID.HasValue ?
                new ObjectParameter("InvoiceTypeID", invoiceTypeID) :
                new ObjectParameter("InvoiceTypeID", typeof(int));
    
            var invoiceNumberParameter = invoiceNumber != null ?
                new ObjectParameter("InvoiceNumber", invoiceNumber) :
                new ObjectParameter("InvoiceNumber", typeof(string));
    
            var billingMonthParameter = billingMonth.HasValue ?
                new ObjectParameter("BillingMonth", billingMonth) :
                new ObjectParameter("BillingMonth", typeof(int));
    
            var billingYearParameter = billingYear.HasValue ?
                new ObjectParameter("BillingYear", billingYear) :
                new ObjectParameter("BillingYear", typeof(int));
    
            var defaultImportCurrencyIDParameter = defaultImportCurrencyID.HasValue ?
                new ObjectParameter("DefaultImportCurrencyID", defaultImportCurrencyID) :
                new ObjectParameter("DefaultImportCurrencyID", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var lastActionParameter = lastAction != null ?
                new ObjectParameter("LastAction", lastAction) :
                new ObjectParameter("LastAction", typeof(string));
    
            var recordType1_StatusParameter = recordType1_Status != null ?
                new ObjectParameter("RecordType1_Status", recordType1_Status) :
                new ObjectParameter("RecordType1_Status", typeof(string));
    
            var recordType1_DateTimeParameter = recordType1_DateTime.HasValue ?
                new ObjectParameter("RecordType1_DateTime", recordType1_DateTime) :
                new ObjectParameter("RecordType1_DateTime", typeof(System.DateTime));
    
            var recordType2_StatusParameter = recordType2_Status != null ?
                new ObjectParameter("RecordType2_Status", recordType2_Status) :
                new ObjectParameter("RecordType2_Status", typeof(string));
    
            var recordType2_DateTimeParameter = recordType2_DateTime.HasValue ?
                new ObjectParameter("RecordType2_DateTime", recordType2_DateTime) :
                new ObjectParameter("RecordType2_DateTime", typeof(System.DateTime));
    
            var recordType3_StatusParameter = recordType3_Status != null ?
                new ObjectParameter("RecordType3_Status", recordType3_Status) :
                new ObjectParameter("RecordType3_Status", typeof(string));
    
            var recordType3_DateTimeParameter = recordType3_DateTime.HasValue ?
                new ObjectParameter("RecordType3_DateTime", recordType3_DateTime) :
                new ObjectParameter("RecordType3_DateTime", typeof(System.DateTime));
    
            var recordType4_StatusParameter = recordType4_Status != null ?
                new ObjectParameter("RecordType4_Status", recordType4_Status) :
                new ObjectParameter("RecordType4_Status", typeof(string));
    
            var recordType4_DateTimeParameter = recordType4_DateTime.HasValue ?
                new ObjectParameter("RecordType4_DateTime", recordType4_DateTime) :
                new ObjectParameter("RecordType4_DateTime", typeof(System.DateTime));
    
            var recordType5_StatusParameter = recordType5_Status != null ?
                new ObjectParameter("RecordType5_Status", recordType5_Status) :
                new ObjectParameter("RecordType5_Status", typeof(string));
    
            var recordType5_DateTimeParameter = recordType5_DateTime.HasValue ?
                new ObjectParameter("RecordType5_DateTime", recordType5_DateTime) :
                new ObjectParameter("RecordType5_DateTime", typeof(System.DateTime));
    
            var billingFileExport_StatusParameter = billingFileExport_Status != null ?
                new ObjectParameter("BillingFileExport_Status", billingFileExport_Status) :
                new ObjectParameter("BillingFileExport_Status", typeof(string));
    
            var billingFileExport_DateTimeParameter = billingFileExport_DateTime.HasValue ?
                new ObjectParameter("BillingFileExport_DateTime", billingFileExport_DateTime) :
                new ObjectParameter("BillingFileExport_DateTime", typeof(System.DateTime));
    
            var billingFileExport_PathParameter = billingFileExport_Path != null ?
                new ObjectParameter("BillingFileExport_Path", billingFileExport_Path) :
                new ObjectParameter("BillingFileExport_Path", typeof(string));
    
            var exportCurrencyIDParameter = exportCurrencyID.HasValue ?
                new ObjectParameter("ExportCurrencyID", exportCurrencyID) :
                new ObjectParameter("ExportCurrencyID", typeof(int));
    
            var serviceDeskSnapshotIDParameter = serviceDeskSnapshotID.HasValue ?
                new ObjectParameter("ServiceDeskSnapshotID", serviceDeskSnapshotID) :
                new ObjectParameter("ServiceDeskSnapshotID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_Invoice", invoiceTypeIDParameter, invoiceNumberParameter, billingMonthParameter, billingYearParameter, defaultImportCurrencyIDParameter, userNameParameter, statusParameter, lastActionParameter, recordType1_StatusParameter, recordType1_DateTimeParameter, recordType2_StatusParameter, recordType2_DateTimeParameter, recordType3_StatusParameter, recordType3_DateTimeParameter, recordType4_StatusParameter, recordType4_DateTimeParameter, recordType5_StatusParameter, recordType5_DateTimeParameter, billingFileExport_StatusParameter, billingFileExport_DateTimeParameter, billingFileExport_PathParameter, exportCurrencyIDParameter, serviceDeskSnapshotIDParameter);
        }
    
        public virtual int insert_InvoiceInMBMAutomate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_InvoiceInMBMAutomate");
        }
    
        public virtual int Insert_MBM_ComparisonResult(Nullable<int> invoiceId, Nullable<int> invoiceTypeId)
        {
            var invoiceIdParameter = invoiceId.HasValue ?
                new ObjectParameter("InvoiceId", invoiceId) :
                new ObjectParameter("InvoiceId", typeof(int));
    
            var invoiceTypeIdParameter = invoiceTypeId.HasValue ?
                new ObjectParameter("InvoiceTypeId", invoiceTypeId) :
                new ObjectParameter("InvoiceTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_MBM_ComparisonResult", invoiceIdParameter, invoiceTypeIdParameter);
        }
    
        public virtual int insert_MBMdata_ByInvoiceIdInvoiceType(Nullable<int> invoiceID, Nullable<int> invoiceTypeID, Nullable<int> fileTypeID, string fileName, string uploadedby, Nullable<int> uploadfileID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            var invoiceTypeIDParameter = invoiceTypeID.HasValue ?
                new ObjectParameter("InvoiceTypeID", invoiceTypeID) :
                new ObjectParameter("InvoiceTypeID", typeof(int));
    
            var fileTypeIDParameter = fileTypeID.HasValue ?
                new ObjectParameter("FileTypeID", fileTypeID) :
                new ObjectParameter("FileTypeID", typeof(int));
    
            var fileNameParameter = fileName != null ?
                new ObjectParameter("FileName", fileName) :
                new ObjectParameter("FileName", typeof(string));
    
            var uploadedbyParameter = uploadedby != null ?
                new ObjectParameter("uploadedby", uploadedby) :
                new ObjectParameter("uploadedby", typeof(string));
    
            var uploadfileIDParameter = uploadfileID.HasValue ?
                new ObjectParameter("uploadfileID", uploadfileID) :
                new ObjectParameter("uploadfileID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_MBMdata_ByInvoiceIdInvoiceType", invoiceIDParameter, invoiceTypeIDParameter, fileTypeIDParameter, fileNameParameter, uploadedbyParameter, uploadfileIDParameter);
        }
    
        public virtual int mbm_FetchCRMDataFromUI(string invoiceNumber, string loggedInUser)
        {
            var invoiceNumberParameter = invoiceNumber != null ?
                new ObjectParameter("InvoiceNumber", invoiceNumber) :
                new ObjectParameter("InvoiceNumber", typeof(string));
    
            var loggedInUserParameter = loggedInUser != null ?
                new ObjectParameter("LoggedInUser", loggedInUser) :
                new ObjectParameter("LoggedInUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("mbm_FetchCRMDataFromUI", invoiceNumberParameter, loggedInUserParameter);
        }
    
        public virtual int Update_InvoiceRecordTypes(Nullable<int> invoiceID, string recordType1Status, string recordType2Status, string recordType3Status, string recordType4Status, string recordType5Status, string lastUpdatedBy)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            var recordType1StatusParameter = recordType1Status != null ?
                new ObjectParameter("RecordType1Status", recordType1Status) :
                new ObjectParameter("RecordType1Status", typeof(string));
    
            var recordType2StatusParameter = recordType2Status != null ?
                new ObjectParameter("RecordType2Status", recordType2Status) :
                new ObjectParameter("RecordType2Status", typeof(string));
    
            var recordType3StatusParameter = recordType3Status != null ?
                new ObjectParameter("RecordType3Status", recordType3Status) :
                new ObjectParameter("RecordType3Status", typeof(string));
    
            var recordType4StatusParameter = recordType4Status != null ?
                new ObjectParameter("RecordType4Status", recordType4Status) :
                new ObjectParameter("RecordType4Status", typeof(string));
    
            var recordType5StatusParameter = recordType5Status != null ?
                new ObjectParameter("RecordType5Status", recordType5Status) :
                new ObjectParameter("RecordType5Status", typeof(string));
    
            var lastUpdatedByParameter = lastUpdatedBy != null ?
                new ObjectParameter("LastUpdatedBy", lastUpdatedBy) :
                new ObjectParameter("LastUpdatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_InvoiceRecordTypes", invoiceIDParameter, recordType1StatusParameter, recordType2StatusParameter, recordType3StatusParameter, recordType4StatusParameter, recordType5StatusParameter, lastUpdatedByParameter);
        }
    
        public virtual int update_ProcessWorkFlowStatus(string invoiceNumber, Nullable<bool> compareToCRM, Nullable<bool> viewChange, Nullable<bool> approveChange, Nullable<bool> syncCRM, Nullable<bool> importCRMData, Nullable<bool> processInvoice, Nullable<bool> exportInvoiceFile)
        {
            var invoiceNumberParameter = invoiceNumber != null ?
                new ObjectParameter("InvoiceNumber", invoiceNumber) :
                new ObjectParameter("InvoiceNumber", typeof(string));
    
            var compareToCRMParameter = compareToCRM.HasValue ?
                new ObjectParameter("CompareToCRM", compareToCRM) :
                new ObjectParameter("CompareToCRM", typeof(bool));
    
            var viewChangeParameter = viewChange.HasValue ?
                new ObjectParameter("ViewChange", viewChange) :
                new ObjectParameter("ViewChange", typeof(bool));
    
            var approveChangeParameter = approveChange.HasValue ?
                new ObjectParameter("ApproveChange", approveChange) :
                new ObjectParameter("ApproveChange", typeof(bool));
    
            var syncCRMParameter = syncCRM.HasValue ?
                new ObjectParameter("SyncCRM", syncCRM) :
                new ObjectParameter("SyncCRM", typeof(bool));
    
            var importCRMDataParameter = importCRMData.HasValue ?
                new ObjectParameter("ImportCRMData", importCRMData) :
                new ObjectParameter("ImportCRMData", typeof(bool));
    
            var processInvoiceParameter = processInvoice.HasValue ?
                new ObjectParameter("ProcessInvoice", processInvoice) :
                new ObjectParameter("ProcessInvoice", typeof(bool));
    
            var exportInvoiceFileParameter = exportInvoiceFile.HasValue ?
                new ObjectParameter("ExportInvoiceFile", exportInvoiceFile) :
                new ObjectParameter("ExportInvoiceFile", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_ProcessWorkFlowStatus", invoiceNumberParameter, compareToCRMParameter, viewChangeParameter, approveChangeParameter, syncCRMParameter, importCRMDataParameter, processInvoiceParameter, exportInvoiceFileParameter);
        }
    
        public virtual int mbm_RecordType1_Process(Nullable<int> invoiceID, string userName, Nullable<int> exportCurrencyID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var exportCurrencyIDParameter = exportCurrencyID.HasValue ?
                new ObjectParameter("ExportCurrencyID", exportCurrencyID) :
                new ObjectParameter("ExportCurrencyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("mbm_RecordType1_Process", invoiceIDParameter, userNameParameter, exportCurrencyIDParameter);
        }
    
        public virtual ObjectResult<mbm_RecordType1_ValidateInvoice_Result> mbm_RecordType1_ValidateInvoice(Nullable<int> invoiceID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mbm_RecordType1_ValidateInvoice_Result>("mbm_RecordType1_ValidateInvoice", invoiceIDParameter);
        }
    
        public virtual int mbm_RecordType2_Process(Nullable<int> invoiceID, string userName, Nullable<int> exportCurrencyID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var exportCurrencyIDParameter = exportCurrencyID.HasValue ?
                new ObjectParameter("ExportCurrencyID", exportCurrencyID) :
                new ObjectParameter("ExportCurrencyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("mbm_RecordType2_Process", invoiceIDParameter, userNameParameter, exportCurrencyIDParameter);
        }
    
        public virtual ObjectResult<mbm_RecordType2_ValidateInvoice_Result> mbm_RecordType2_ValidateInvoice(Nullable<int> invoiceID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mbm_RecordType2_ValidateInvoice_Result>("mbm_RecordType2_ValidateInvoice", invoiceIDParameter);
        }
    
        public virtual int insert_InvoiceByMBMAutomate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_InvoiceByMBMAutomate");
        }
    
        public virtual int PostBillingInMBMAutomate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PostBillingInMBMAutomate");
        }
    
        public virtual ObjectResult<Nullable<int>> insert_InvoiceByMBMAutomate_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("insert_InvoiceByMBMAutomate_all");
        }
    
        public virtual int insert_InvoiceByMBMAutomate_Process(Nullable<int> invoiceTypeId)
        {
            var invoiceTypeIdParameter = invoiceTypeId.HasValue ?
                new ObjectParameter("InvoiceTypeId", invoiceTypeId) :
                new ObjectParameter("InvoiceTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_InvoiceByMBMAutomate_Process", invoiceTypeIdParameter);
        }
    
        public virtual int ApplicationLog_Get(Nullable<int> maxRowsReturned)
        {
            var maxRowsReturnedParameter = maxRowsReturned.HasValue ?
                new ObjectParameter("MaxRowsReturned", maxRowsReturned) :
                new ObjectParameter("MaxRowsReturned", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ApplicationLog_Get", maxRowsReturnedParameter);
        }
    
        public virtual int ApplicationLog_InsertItem(Nullable<int> invoiceID, string userName, Nullable<System.DateTime> exceptionDateTime, string codeLocation, string comment, string message, string source, string targetSite, string stackTrace, Nullable<int> logType)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var exceptionDateTimeParameter = exceptionDateTime.HasValue ?
                new ObjectParameter("ExceptionDateTime", exceptionDateTime) :
                new ObjectParameter("ExceptionDateTime", typeof(System.DateTime));
    
            var codeLocationParameter = codeLocation != null ?
                new ObjectParameter("CodeLocation", codeLocation) :
                new ObjectParameter("CodeLocation", typeof(string));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("Message", message) :
                new ObjectParameter("Message", typeof(string));
    
            var sourceParameter = source != null ?
                new ObjectParameter("Source", source) :
                new ObjectParameter("Source", typeof(string));
    
            var targetSiteParameter = targetSite != null ?
                new ObjectParameter("TargetSite", targetSite) :
                new ObjectParameter("TargetSite", typeof(string));
    
            var stackTraceParameter = stackTrace != null ?
                new ObjectParameter("StackTrace", stackTrace) :
                new ObjectParameter("StackTrace", typeof(string));
    
            var logTypeParameter = logType.HasValue ?
                new ObjectParameter("LogType", logType) :
                new ObjectParameter("LogType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ApplicationLog_InsertItem", invoiceIDParameter, userNameParameter, exceptionDateTimeParameter, codeLocationParameter, commentParameter, messageParameter, sourceParameter, targetSiteParameter, stackTraceParameter, logTypeParameter);
        }
    
        public virtual int ExceptionLog_Get(Nullable<int> maxRowsReturned)
        {
            var maxRowsReturnedParameter = maxRowsReturned.HasValue ?
                new ObjectParameter("maxRowsReturned", maxRowsReturned) :
                new ObjectParameter("maxRowsReturned", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ExceptionLog_Get", maxRowsReturnedParameter);
        }
    
        public virtual int ExceptionLog_InsertItem(Nullable<int> invoiceID, string type, string comment, string stackTrace, string createdBy)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var stackTraceParameter = stackTrace != null ?
                new ObjectParameter("StackTrace", stackTrace) :
                new ObjectParameter("StackTrace", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ExceptionLog_InsertItem", invoiceIDParameter, typeParameter, commentParameter, stackTraceParameter, createdByParameter);
        }
    
        public virtual ObjectResult<ProcessLog_Get_Result> ProcessLog_Get(Nullable<int> invoiceID, Nullable<int> maxRowsToReturn)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            var maxRowsToReturnParameter = maxRowsToReturn.HasValue ?
                new ObjectParameter("MaxRowsToReturn", maxRowsToReturn) :
                new ObjectParameter("MaxRowsToReturn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcessLog_Get_Result>("ProcessLog_Get", invoiceIDParameter, maxRowsToReturnParameter);
        }
    
        public virtual int ProcessLog_InsertItem(Nullable<int> invoiceID, string processName, string processResult, Nullable<System.DateTime> processDateTime, string comment, string createdBy)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            var processNameParameter = processName != null ?
                new ObjectParameter("ProcessName", processName) :
                new ObjectParameter("ProcessName", typeof(string));
    
            var processResultParameter = processResult != null ?
                new ObjectParameter("ProcessResult", processResult) :
                new ObjectParameter("ProcessResult", typeof(string));
    
            var processDateTimeParameter = processDateTime.HasValue ?
                new ObjectParameter("ProcessDateTime", processDateTime) :
                new ObjectParameter("ProcessDateTime", typeof(System.DateTime));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcessLog_InsertItem", invoiceIDParameter, processNameParameter, processResultParameter, processDateTimeParameter, commentParameter, createdByParameter);
        }
    
        public virtual ObjectResult<PostBillingInMBMAutomate_GetInvoiceRecords_Result> PostBillingInMBMAutomate_GetInvoiceRecords()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PostBillingInMBMAutomate_GetInvoiceRecords_Result>("PostBillingInMBMAutomate_GetInvoiceRecords");
        }
    
        public virtual int update_MBMAutomateStatus(Nullable<int> invoiceId, Nullable<bool> value, string statusOf)
        {
            var invoiceIdParameter = invoiceId.HasValue ?
                new ObjectParameter("InvoiceId", invoiceId) :
                new ObjectParameter("InvoiceId", typeof(int));
    
            var valueParameter = value.HasValue ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(bool));
    
            var statusOfParameter = statusOf != null ?
                new ObjectParameter("StatusOf", statusOf) :
                new ObjectParameter("StatusOf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_MBMAutomateStatus", invoiceIdParameter, valueParameter, statusOfParameter);
        }
    
        public virtual int usp_mbm_CBADCRMData(Nullable<int> invoiceID, string loggedInUser)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            var loggedInUserParameter = loggedInUser != null ?
                new ObjectParameter("LoggedInUser", loggedInUser) :
                new ObjectParameter("LoggedInUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_mbm_CBADCRMData", invoiceIDParameter, loggedInUserParameter);
        }
    
        public virtual int usp_mbm_CBADTaxData(Nullable<int> invoiceID, string loggedInUser)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            var loggedInUserParameter = loggedInUser != null ?
                new ObjectParameter("LoggedInUser", loggedInUser) :
                new ObjectParameter("LoggedInUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_mbm_CBADTaxData", invoiceIDParameter, loggedInUserParameter);
        }
    
        public virtual int usp_mbm_GetMultiLocationSummaryData(Nullable<int> invoiceId, string loggedInUser)
        {
            var invoiceIdParameter = invoiceId.HasValue ?
                new ObjectParameter("InvoiceId", invoiceId) :
                new ObjectParameter("InvoiceId", typeof(int));
    
            var loggedInUserParameter = loggedInUser != null ?
                new ObjectParameter("LoggedInUser", loggedInUser) :
                new ObjectParameter("LoggedInUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_mbm_GetMultiLocationSummaryData", invoiceIdParameter, loggedInUserParameter);
        }
    
        public virtual int mbm_RecordType3_Process(Nullable<int> invoiceID, string userName, Nullable<int> exportCurrencyID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var exportCurrencyIDParameter = exportCurrencyID.HasValue ?
                new ObjectParameter("ExportCurrencyID", exportCurrencyID) :
                new ObjectParameter("ExportCurrencyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("mbm_RecordType3_Process", invoiceIDParameter, userNameParameter, exportCurrencyIDParameter);
        }
    
        public virtual int mbm_RecordType4_Process(Nullable<int> invoiceID, string userName, Nullable<int> exportCurrencyID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var exportCurrencyIDParameter = exportCurrencyID.HasValue ?
                new ObjectParameter("ExportCurrencyID", exportCurrencyID) :
                new ObjectParameter("ExportCurrencyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("mbm_RecordType4_Process", invoiceIDParameter, userNameParameter, exportCurrencyIDParameter);
        }
    
        public virtual int mbm_RecordType5_Process(Nullable<int> invoiceID, string userName, Nullable<int> exportCurrencyID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var exportCurrencyIDParameter = exportCurrencyID.HasValue ?
                new ObjectParameter("ExportCurrencyID", exportCurrencyID) :
                new ObjectParameter("ExportCurrencyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("mbm_RecordType5_Process", invoiceIDParameter, userNameParameter, exportCurrencyIDParameter);
        }
    
        public virtual int mbm_RT1Summary_Process(Nullable<int> invoiceID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("mbm_RT1Summary_Process", invoiceIDParameter);
        }
    
        public virtual int mbm_RT2Summary_Process(Nullable<int> invoiceID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("mbm_RT2Summary_Process", invoiceIDParameter);
        }
    
        public virtual int mbm_RT4Summary_Process(Nullable<int> invoiceID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("mbm_RT4Summary_Process", invoiceIDParameter);
        }
    }
}
