//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automate.DataAccess.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class mbm_ProcessWorkFlowStatus
    {
        public int Id { get; set; }
        public string sInvoiceNumber { get; set; }
        public bool sCompareToCRM { get; set; }
        public bool sViewChange { get; set; }
        public bool sApproveChange { get; set; }
        public bool sSyncCRM { get; set; }
        public bool sImportCRMData { get; set; }
        public bool sProcessInvoice { get; set; }
        public bool sExportInvoiceFile { get; set; }
    }
}
