//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automate.DataAccess.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessLog
    {
        public int ID { get; set; }
        public int InvoiceID { get; set; }
        public string ProcessName { get; set; }
        public string ProcessResult { get; set; }
        public System.DateTime ProcessDateTime { get; set; }
        public string Comment { get; set; }
        public string CreatedBy { get; set; }
    }
}
