//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIAutomateMBM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MBMAutomateStatu
    {
        public int ID { get; set; }
        public int InvoiceTypeId { get; set; }
        public int ImportCurrencyId { get; set; }
        public int ExportCurrenyId { get; set; }
        public int BillingMonth { get; set; }
        public int BillingYear { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string InvoiceNumber { get; set; }
        public bool IsInvoiceCreated { get; set; }
        public bool IsFileTypeUploaded { get; set; }
        public bool IsComparedToCRM { get; set; }
        public bool IsViwedChanged { get; set; }
        public bool IsApprovedChange { get; set; }
        public bool IsApprovalMailSent { get; set; }
        public bool IsNewInvoice { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public bool IsManualFileUpload { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<bool> IsApprovedByMail { get; set; }
    }
}
