//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIAutomateMBM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MBMDb : DbContext
    {
        public MBMDb()
            : base("name=MBMDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mbm_ProcessWorkFlowStatus> mbm_ProcessWorkFlowStatus { get; set; }
        public DbSet<TokenHistory> TokenHistories { get; set; }
        public DbSet<MBMAutomateStatu> MBMAutomateStatus { get; set; }
    }
}
